### ISSUE TITLE
How to goto the web page?

### ISSUE THREAD

**Issue by jie-xiao** [sgabe/winaflpet#2]
now I run docker in linux and agent in Windows,but cannot find the web page,there is some  screenshot:
![image](https://user-images.githubusercontent.com/22072664/111122515-20ba9c80-85a9-11eb-8221-ea980846d7ed.png)
![image](https://user-images.githubusercontent.com/22072664/111122574-30d27c00-85a9-11eb-9c3b-b74b0b4963f1.png)
![image](https://user-images.githubusercontent.com/22072664/111122631-4051c500-85a9-11eb-964f-d4d846cc0726.png)
any suggestion?
and also,I tried to change the listening port,but no result,it still use 4141

**Comment by jie-xiao** [comment]
run server in windows,it works...but I cannot log in,for the function to get password is os.hostname()?
![image](https://user-images.githubusercontent.com/22072664/111135849-19e75600-85b8-11eb-88a6-a3a7f8ecefd1.png)

**Comment by sgabe** [comment]
By default, the server is intended to be run on Linux in a Docker container where the initial password (ensure to change it after the login) of the default `admin` user will be either:
- the container ID (the UUID short identifier, e.g. `f78375b1c487`)  or
- the container name assigned with the `--name` option.

You can map the default container port `4141` to a port on the Linux host running Docker to make it available for the outside world (e.g. from another Windows host).

```
docker run -p 192.168.0.1:8080:4141 \
    -v /path/to/winaflpet/data:/opt/winaflpet/data \
    sgabe/winaflpet
```

However, you should be able to change the listen address and the port number by:
- using the `--host` and `--port` command line flags (recently fixed) or
- setting the environment variables `WINAFLPET_HOST` and `WINAFLPET_PORT` or
- creating a `winaflpet.yml` configuration file in the `data` directory including:

```
server:
  host: "192.168.43.43"
  port: 4343
```

**Comment by jie-xiao** [comment]
https://stackoverflow.com/questions/59551646/how-to-set-a-cookie-with-gin-jwt-middleware

**Comment by jie-xiao** [comment]
> ，您应该能够通过以下方式更改侦听地址和端口号：
I have given up using linux, and the token cannot be delivered due to the inability to provide a secure connection on windows, causing the login to be redirected back to the original web page. Currently, SecureCookie is modified to false. Can log in successfully

**Comment by jie-xiao** [comment]
I have given up using linux, and the token cannot be delivered due to the inability to provide a secure connection on windows, causing the login to be redirected back to the original web page. Currently, SecureCookie is modified to false. Can log in successfully

**Comment by sgabe** [comment]
Note that locally-delivered resources such as those with the default `http://127.0.0.1:4141` URLs are considered to have been delivered securely. However, I have added a `--debug` flag to enable debug mode and a non-secure session cookie.
